# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vllm-service:
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.10.1
    container_name: vllm-service
    ports:
      - "8086:8000"
    volumes:
      - ${HF_CACHE_DIR:-./data}:/data
    shm_size: 128g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HF_TOKEN}
      HF_HOME: ./data
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      VLLM_TORCH_PROFILER_DIR: "/mnt"
      HF_HUB_OFFLINE: ${HF_HUB_OFFLINE:-0}
      VLLM_CPU_KVCACHE_SPACE: 40
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://$HOST_IP:8086/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
    command: --model ${LLM_MODEL_ID} --host 0.0.0.0 --port 8000
