# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# [IP_ADDR]:{PORT_OUTSIDE_CONTAINER} -> {PORT_INSIDE_CONTAINER} / {PROTOCOL}
global:
  scrape_interval: 5s
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "vllm"
    metrics_path: /metrics
    static_configs:
      - targets: ["vllm-gaudi-server:8000"]
  - job_name: "worker-rag-agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["rag-agent-endpoint:9095"]
  - job_name: "worker-sql-agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["sql-agent-endpoint:9096"]
  - job_name: "supervisor-react-agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["react-agent-endpoint:9090"]
  - job_name: "prometheus-node-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus-gaudi-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["gaudi-exporter:41611"]
