# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  tei-embedding-service:
    image: ghcr.io/huggingface/tei-gaudi:1.5.0
    container_name: tei-embedding-gaudi-server
    ports:
      - "8090:80"
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    shm_size: 1g
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      MAX_WARMUP_SEQUENCE_LENGTH: 512
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate
